//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabImages
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoCategoryCode
    {
        public string CategoryCode { get; set; }
        public string CategoryDesc { get; set; }
        public string MainCategory { get; set; }
        public string BaseYN { get; set; }
        public string ExteriorYN { get; set; }
        public string InteriorYN { get; set; }
        public string GrassYN { get; set; }
        public string SnowYN { get; set; }
        public string WinterizationYN { get; set; }
        public string InitialSecureYN { get; set; }
        public string ConvCondYN { get; set; }
    }
}
