//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabImages
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLoanImage
    {
        public int IMAGEID { get; set; }
        public string LoanNumber { get; set; }
        public string MortgageCompany { get; set; }
        public string IMAGETYPE { get; set; }
        public string WhoScanned { get; set; }
        public Nullable<System.DateTime> DateScanned { get; set; }
        public string ImageMemo { get; set; }
        public Nullable<int> SeqNumber { get; set; }
        public Nullable<int> WONUMBER { get; set; }
        public string WDOCID { get; set; }
        public Nullable<short> NumPages { get; set; }
        public Nullable<int> GrassNumber { get; set; }
        public byte[] upsize_ts { get; set; }
        public Nullable<System.DateTime> dt_photo { get; set; }
        public string itemCode { get; set; }
        public string BeforeAft { get; set; }
        public string StatusCode { get; set; }
        public string LocationCode { get; set; }
        public string FloorCode { get; set; }
    }
}
